env:
    global:
        - REPO_DIR=yt
        # Commit from your-project that you want to build
        - BUILD_COMMIT=yt-3.6.1
        # Non-numpy or testing dependencies
        - GEN_DEPENDS="setuptools sympy matplotlib"
        - PLAT=x86_64
        - UNICODE_WIDTH=32

language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
sudo: required
dist: trusty
services: docker

before_install:
    - BUILD_DEPENDS="$NP_BUILD_DEP Cython"
    - TEST_DEPENDS="$NP_TEST_DEP nose $GEN_DEPENDS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

jobs:
  include:
    - stage: tests
      os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.15.4
        - NP_TEST_DEP=numpy==1.15.4
    
    - stage: tests
      os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.16.5
        - NP_TEST_DEP=numpy==1.16.5
    
    - stage: tests
      os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.5
        - NP_TEST_DEP=numpy==1.17.5
    
    - stage: tests
      os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.15.4
        - NP_TEST_DEP=numpy==1.15.4
    
    - stage: tests
      os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.16.5
        - NP_TEST_DEP=numpy==1.16.5
    
    - stage: tests
      os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.5
        - NP_TEST_DEP=numpy==1.17.5

script:
    - install_run $PLAT

after_success:
    # Upload the generated wheels to anaconda.org/multibuild-wheels-staging
    # using YT_STAGING_UPLOAD_TOKEN which is set as an environment variable 
    # in the travis CI configuration settings. The current token was generated 
    # by munkm at https://anaconda.org/multibuild-wheels-staging/settings/access
    #
    - TOKEN=${YT_STAGING_UPLOAD_TOKEN};
    - python -m pip install git+https://github.com/Anaconda-Server/anaconda-client;
    - if [ -n "${TOKEN}" ] ; then
        anaconda -t ${TOKEN} upload -u "multibuild-wheels-staging" ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl;
      fi
